Create table Mine (
    songName		varchar2(250),
    Artist          varchar2(250),
    Composer        varchar2(250),
    Album           varchar2(250),
    theGrouping     varchar2(250),
    Genre           varchar2(250),
    theSize         integer,
    theTime         integer,
    DiscNumber      integer,
    DiscCount       integer,
    TrackNumber     integer,
    TrackCount      integer,
    theYear         integer,
    DateModified	date,
    DateAdded       date,
    BitRate         integer,
    SampleRate      integer,
    VolumeAdjustment    integer,
    Kind            varchar2(250),
    Equalizer       integer,
    Comments        integer,
    Plays           integer,
    LastPlayed      date,
    Skips           integer,
    LastSkipped     date,
    MyRating        varchar2(250),
    diskLocation    varchar2(500)
)

